print('hello')
print('hello')
print('a test of git with vscode')
print('I changed it in github')
print('it is in hot-fix branch...')
print('in hot-fix2')
print('now I in master and washing a conflict')